### ISSUE TITLE
Mario example is not running

### ISSUE THREAD

**Issue by skprasadu** [jamesmacaulay/zelkova#2]
Hi James, I am trying to run the Mario example and I am getting some errors, below are the steps to reproduce,

a. On the Zelkova root, I did "lein install"
b. On the example/mario folder I did "lein cljsbuild once"

I got following warnings, WARNING: Use of undeclared Var jamesmacaulay.zelkova.signal/update at line 347 file:/C:/Users/v-krsrin/.m2/repository/jamesmacaulay/zelkova/0.2.1-SNAPSHOT/zelkova-0.2.1-SNAPSHOT.jar!/jamesmacaulay/zelkova/signal.cljs

Finally when I opened the index.html in the browser, I got, 

Uncaught TypeError: Cannot read property 'call' of undefinedcore.cljs:119 (anonymous function)core.cljs:124 (anonymous function)

**Comment by jamesmacaulay** [comment]
I just pushed a rebuilt version based on [figwheel-template](https://github.com/bhauman/figwheel-template). If you pull the latest master, you can run the new version with `lein figwheel`. Let me know if that fixes it for you!

For what it's worth, I never got the errors you got...but I got other errors that also prevented me from running the example on master. The errors you got look like they might have come from a mismatched version of Clojure or ClojureScript, since the `update` function is a new addition to the language.

**Comment by skprasadu** [comment]
It works like a charm, thanks..
