### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by dubiousdavid** [jamesmacaulay/zelkova#7]
Please add API documentation. I'd be happy to help. Just let me know.

David

**Comment by sparkofreason** [comment]
+1

**Comment by bensu** [comment]
@jamesmacaulay would you be ok with (codox)[https://github.com/weavejester/codox] or (marginalia)[https://github.com/gdeer81/marginalia]?

**Comment by jamesmacaulay** [comment]
Yeah, I think codox generated in the gh-pages branch and then linked from the README makes sense.

**Comment by bensu** [comment]
This in now [work in progress](https://github.com/funcool/codeina/pull/2). Both codox and codeina needed work in order to support a `cljc` codebase. I chose codeina instead of codox because it does not attempt to be backwards compatible with earlier Clojure version, making the refactoring much easier.

@jamesmacaulay if you are interested in publishing the docs before the PR is merged and deployed let me know.

**Comment by jamesmacaulay** [comment]
Thanks @bensu! Sounds great. We can wait a few days/a week, then go ahead with doc generation from your fork if that PR hasn't been merged by then.
